# .github/workflows/deploy-to-s3.yml
name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      # 3. (optional) build step
      # - name: Build project
      #   run: npm ci && npm run build

      # 4. sync files to S3
      - name: Sync files to S3
        run: |
          aws s3 sync ./public \
            s3://${{ secrets.S3_BUCKET_NAME }} \
            --acl public-read